// vue-apollo-client/src/components/BookDetails.vue
<template>
  <v-flex xs4 offset-xs4>
    <v-card dark color="purple" v-if="book">
      <v-card-text class="display-2">Title: {{ book.name }}</v-card-text>
      <v-card-text class="headline">Genre: {{ book.genre }}</v-card-text>
      <v-card-text class="headline">Author: {{ book.author.name }}</v-card-text>
      <v-card-text class="headline">
        <v-list>
          <v-list-tile-content class="px-3">
            <v-list-tile-title>All Books</v-list-tile-title>
            <v-list-tile-sub-title v-for="book in book.author.books" :key="book.id">{{ book.name }}</v-list-tile-sub-title>
          </v-list-tile-content>
        </v-list>
      </v-card-text>
    </v-card>
  </v-flex>
</template>
<script>
import { getBookQuery } from '@/queries/books'
export default {
  props: {
    id: {
      type: String,
      require: true
    }
  },
  apollo: {
    book: {
      query: getBookQuery,
      variables() {
        return {
          id: this.id
        }
      },
      deep: false
    }
  },
  
  data: () => ({}),
}
</script>

// react-apollo-client/src/components/BookDetails.js
import React, { Component } from 'react';
import { graphql } from 'react-apollo';
import { getBookQuery } from '../queries/queries';

class BookDetails extends Component {
  displayBookDetails() {
    const { book } = this.props.data
    if(book) {
      return (
        <div>
          <h2>{book.name}</h2>
          <p>{book.genre}</p>
          <p>{book.author.name}</p>
          <p>All boks by this author:</p>
          <ul className="other-books">
            {book.author.books.map(item => {
              return <li key={item.id}>{item.name}</li>
            })}
          </ul>
        </div>
      )
    } else {
      return(
        <div>No books selected...</div>
      )
    }
  }
  render() {
    return (
      <div id="book-details">
        {this.displayBookDetails()}
      </div>
    );
  }
}

export default graphql(getBookQuery, {
  options: (props) => {
    return {
      variables: {
        id: props.bookId
      }
    }
  }
})(BookDetails);
